spring.application.name=payment-provider

# Настройки подключения к RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Настройка автоматического перевода Java-объектов в JSON при отправке в очередь
spring.mvc.converters.preferred-json-mapper=jackson